spring:
  application:
    name: ColorToMQTTApp
app:
  defaultSettings:
    screenHeight: 400
    screenWight: 400
    updatePeriod: 500 #ms
    sensitivity: 50 #min 0 max 100
    processor: chessProcessor #chessProcessor
    detector: averageColorDetector #averageColorDetector
    screenAreaType: centeredArea
    cellSize: 20
    #MQTT
    broker: "tcp://192.168.0.126:1883"
    topic: colorToMQTT
    username: mqtt-user
    password: 123qwe123QWE

    minHUE: 0
    maxHUE: 360
    minSaturation: 0
    maxSaturation: 100
    minBrightness: 200
    maxBrightness: 0

