spring:
  application:
    name: ColorToMQTTApp
app:
  defaultSettings:
    screenHeight: 400
    screenWight: 400
    updatePeriod: 500 #ms
    sensitivity: 50 #min 0 max 100
    processor: chessProcessor #chessProcessor
    detector: averageColorDetector #averageColorDetector
    screenAreaType: centeredArea
    cellSize: 20

    minHUE: 0
    maxHUE: 360
    minSaturation: 0
    maxSaturation: 100
    minBrightness: 200
    maxBrightness: 0
#    HUECoefficient: 360
#    saturationCoefficient: 100
#    brightnessCoefficient: 255
#    sensitivityCoefficient: 20
    mqtt_server: mqtt-server
    mqtt_port: 1883
    mqtt_topic: colorToMQTT
    mqtt_username: mqtt_user
    mqtt_password: 12345

